module.exports = {
  printWidth: 80,
  tabWidth: 2,
  useTabs: false,
  semi: true,
  singleQuote: true,
  quoteProps: 'as-needed',
  trailingComma: 'all',
  bracketSpacing: true,
  arrowParens: 'avoid',
  requirePragma: false,
  proseWrap: 'preserve',
  endOfLine: 'auto',
  parser: 'babel',
};